---
AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 bucket
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: <YOUR-BUCKET-NAME>
      WebsiteConfiguration:
       IndexDocument: index.html
       ErrorDocument: error.html

  SampleBucketPolicy:
   Type: AWS::S3::BucketPolicy
   Properties:
     Bucket: !Ref S3Bucket
     PolicyDocument:
       Statement:
          - Sid: "St281144"
            Action: "s3:*"
            Effect: "Allow"
            Resource: !Join ['', ['arn:aws:s3:::', !Ref S3Bucket, '/*']]
            Principal:
              AWS: !Join ['', ["arn:aws:iam::<YOUR-ACCOUNT-ID>", ":root"]]
