AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Flavor:
    Type: String
    Default: "lab"
  classAppDynamoDBTablePITR:
    Type: String
    Default: true
    AllowedValues: [true, false]
    Description: "PointInTimeRecoveryEnabled for class-DynamoDB-Apps"

Resources:
  classAppDynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: "authCode"
          AttributeType: "S"
      KeySchema:
      - AttributeName: "authCode"
        KeyType: "HASH"
      TableName: !Sub
      - class-<app>-code-${Flavour}
      - { Flavour: !Ref Flavor }
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !Ref classAppDynamoDBTablePITR
      TimeToLiveSpecification:
        AttributeName: "expirationTime"
        Enabled: true
